micronaut:
  server:
    netty:
      worker:
        shutdown:
          quiet-period: 300ms
          timeout: 300ms
  application:
    name: jllama
  codec:
    json:
      additional-types:
        - application/x-ndjson
  http:
    client:
      read-timeout: 300s