micronaut:
  application:
    name: ollama-cli
  codec:
    json:
      additional-types:
        - application/x-ndjson
  http:
    client:
      read-timeout: 30s
  
ollama:
  props:
    api-url: ${ollama.api.url:`http://localhost:11434`}